name: Docker CI/CD

on:
  push:
    branches:
      - '*'
    paths:
      - 'node-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set branch name as an environment variable
        run: echo "DEPLOYED_FROM=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build --build-arg DEPLOYED_FROM=$DEPLOYED_FROM -t sumitbera000/node-app:latest .
          docker push sumitbera000/node-app:latest

